Dilden/helth

package-lock.json
package.json
src/components/charts/Chart.svelte
svelte.config.js

Show horizontal lines on charts where goals/limits are

Moar charts

---

src/components/Modal.svelte
src/components/counts/Counter.svelte
src/components/nav/Menu.svelte

Disables on menu link, scanner modal open button, and counter buttons. Resolves #54

Disable double-tap to zoom

---

src/components/Barcode.svelte
src/components/Helth.svelte
src/components/Modal.svelte
src/components/nav/Menu.svelte
src/components/nav/Navigation.svelte
static/global.css

Tamed colors in global css, adjusted nav + menu, set header compnents to use global css vars.

Styling changes

---

.gitignore
package.json
src/components/ReloadPrompt.svelte
src/components/data/ExportData.svelte
src/components/data/ImportData.svelte
src/components/nav/Footer.svelte
src/components/nav/Menu.svelte
src/routes/data/+page.svelte
src/stores/local.js
vite.config.js

A new route has been added (/data) that allows a user to export their current data or import data to overwrite their current data.

Import + export

---

package-lock.json
package.json
src/routes/+layout.js
svelte.config.js

SvelteKit has reached 1.0 which means stability should be better and future upgrades should be easier. This PR closes #75

SvelteKit 1.0

---

package-lock.json
package.json
src/lib/charts/Chart.svelte

Upgraded all dependencies to be latest versions, consequences be damned!

Dependencies

---

src/routes/+layout.svelte
src/stores/db.js
src/utils/toast.js
tests/adddialog.test.js

Enable persistent storage to keep browser from clearing user data. Resolves #97

Persistent Storage

---

src/lib/Barcode.svelte
src/lib/inventory/Item.svelte
src/routes/api/upc/+server.js
src/utils/toast.js

If an item isn't found during the barcode API lookup, show the user an errorToast and do not add an empty object to the inventory. Resolves #105.

Scanning - show errors

---

package-lock.json
package.json
svelte.config.js

Changed sveltekit adapter to deploy to cloudflare

Initial commit for deploying to cloudflare pages

---

package-lock.json
package.json
vite.config.js

Upgraded dependency https://github.com/vite-pwa/sveltekit, https://vite-pwa-org.netlify.app/frameworks/sveltekit.html

Upgrading Vite PWA SvelteKit plugin to @vite-pwa/sveltekit

---

src/lib/counts/counter.test.js
src/lib/inventory/List.svelte
src/lib/inventory/Search.svelte
static/global.css
tests/adddialog.test.js

Plus, I forgot to make some adjustments to tests when incorporating a11y tweaks.

Inventory mobile

---

src/lib/recipes/RecipeForm.svelte
src/lib/recipes/recipeform.test.js

Show users a message if there is no inventory supplied. 

---

package.json
src/lib/Barcode.svelte
src/routes/+layout.svelte
src/routes/about/+page.svelte
src/stores/db.js

When attempting to open the barcode scanner on iOS, the controls would be covered. I guess WebKit didn't like percentages in grid-row sizing.
Also addressed an issue on iOS where persistent storage would never be enabled, even if a user wanted to.
Resolves #140

iOS issues

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
src/routes/about/+page.svelte

Also mentioned changes in latest version cause I forget to do that all the time.

Pull request template added

---

package-lock.json
package.json
src/lib/data/ExportData.svelte
src/lib/data/ImportData.svelte
src/routes/about/+page.svelte
src/stores/stores.js

Can now export data from Dexie via dexie-export-import package that gets data as a blob and puts it into a URL Object.

Export + Import

---

src/lib/counts/Counter.svelte
src/routes/about/+page.svelte
src/routes/charts/+page.svelte
src/routes/settings/+page.svelte
vite.config.js

Stopped using .container class as that's something used by Tailwind.

---

src/lib/recipes/RecipeForm.svelte

Better alignment of grid items

---

src/lib/nav/Menu.svelte

Added clickOutside functionality to Nav Menu

---

src/stores/stores.js
src/utils/item.ts

These changes ensure that derived store values are calculated without modifying its constituent stores.

Avoid compounding calculations by making copies of objects from the store

---

package-lock.json
package.json
src/lib/Date.svelte
src/lib/counts/Counter.svelte
src/lib/data/ImportData.svelte
src/lib/misc/DatePicker.svelte
src/lib/misc/datepicker.test.ts
src/routes/about/+page.svelte
src/routes/page.test.ts
src/routes/settings/+page.svelte
src/stores/db.js
src/stores/stores.js
src/stores/stores.test.js
src/utils/dates.test.ts
src/utils/dates.ts

New datepicker component for changing date data is being entered for.

---

package-lock.json
package.json
src/routes/+layout.js
src/routes/+layout.svelte
src/routes/+layout.ts
src/routes/about/+page.svelte

Issue #204
